### PR TITLE
Look Enhancement in buttons (Please review)

### PR DESCRIPTION
**Pull request by Ritvyk**
:hover selector is added in the index.css

### CODE REVIEW

**Comment by thisisayush** [comment]
Hi Ritvyk, can you post a screenshot of how it looks?

**Comment by Ritvyk** [comment]
@thisisayush You can take reference from the PR #358 , Don't Bother dropdowns , because drop downs are not in this PR , 
enhancements : Hover,Transform into buttons with a simple border.

**Comment by Ritvyk** [comment]
waybak
@thisisayush Thanks buddy!
btw Can you merge this PR.

**Comment by MaxReinisch** [comment]
2 things: I don't think the border is necessary, and it *might* look better if it were animated instead of instant.

**Comment by anishsarangi** [comment]
Thank you for this PR. But now we are moving in different direction regarding this UI. We can close this PR. If you feel any other improvements need to be done, please make a PR.

**Pull request closed without merging**
