### PR TITLE
Bug fix for SPN and auto-save

### PR DESCRIPTION
**Pull request by cgorringe**
- Save Page Now button works again.
- Auto-save works.
- Toolbar icon changes to red 'S' during save, then a checkmark when finished saving.

### CODE REVIEW

**Comment by cgorringe** [comment]
Realized I need to do 2 more things:
- [ ] Test and Abort auto_save() if no Internet connection (i.e. offline).
- [ ] Ensure that auto-save is disabled if not logged in.

**Comment by anishsarangi** [comment]
@cgorringe The save API will not work if you have not been logged in.

**Comment by anishsarangi** [comment]
Good to go !! Working fine for me .

**Comment by cgorringe** [comment]
Currently, if not logged in and when auto-save is enabled, it'll briefly show the 'S' icon as it calls the save API, then quickly go back to the default icon. It doesn't cause any issues so I'm going to leave it as-is for now. We can revisit checking first if already logged-in after completing #507.

**Pull request merged**
