### PR TITLE
(add) Context Selection Check before sending showall signal

### PR DESCRIPTION
**Pull request by thisisayush**
Refer #339 

#### Normal
image

#### *OnClick* if context is not available
image

This reverts back to original within one second.

### CODE REVIEW

**Comment by MaxReinisch** [comment]
Wouldn't it make more sense to check if any of the settings are true (logical or) and if not, just hide the button entirely?

**Comment by thisisayush** [comment]
I initially thought the same, but then the user will probably never know about the feature, imo.

**Comment by sr6033** [comment]
Let's think of a workaround for it. Something that will let the user know and also won't show the button unless checked.

**Comment by MaxReinisch** [comment]
How about leaving the button text the same, but graying it out and adding an explanation popup/title on hover.  Something like "Enable context features in settings"

**Comment by thisisayush** [comment]
@MaxReinisch That sounds cool. I was thinking that instead of Showing this, How about we create a startup guide that launches before the agreement, that will involve configuring the Extension (if not already) with Info on what each option mean and then we show up the agreement?

In this way, the user will also get familiar with extension and we'll have contexts ready. So if the user has not selected any context, hiding the button will now make sense.

**Comment by sr6033** [comment]
@thisisayush that can be a workaround but won't that be a bit heavy in terms of UX as it may bore the user to start configuring so much in the first run itself.

**Comment by thisisayush** [comment]
I don't think that would be heavy, plus we'll be requiring user to do the minimum config, I personally came to know about what the context button does after some time when I randomly clicked those checkboxes in the settings

**Comment by tanweer919** [comment]
@thisisayush How about adding a dropdown to manually select the feature the user wants to run. Because right now, on clicking the button all the selected feature pops out at once. This may hamper user experience.

**Comment by sr6033** [comment]
Drop down will become a big list....and adding such a big drop down in an extension is generally not recommended.

**Comment by tanweer919** [comment]
And how about, when the context button is clicked, we show a popup or a modal to select the context feature that the user wants to run. Because executing the features all at once as happening right now may not be very user friendly.

**Comment by sr6033** [comment]
@tanweer919 even now the user selects what features to be shown. But I understand what you mean by that and that can be a good idea for UX. I will think about it and comment a solution.

**Comment by tanweer919** [comment]
Yes the user can still select the featues to be shown, but for this they have to go within the settings option. I think we can make it simpler.

**Comment by MaxReinisch** [comment]
I agree that the current way the feature works is not a great user experience.  However, it is the way the idea was conceived, and we've been discussing how to improve the feature overall.  While this discussion has been great, I'd like to see something be done with the UI now because the overall issue of "Having a button that does nothing when no settings are on" is really bad UI.  

I will open an issue regarding overall context ui ideas.  But for now, I'd like to see the "gray out + suggestion to turn on context features in the settings" idea committed @tanweer919

**Comment by thisisayush** [comment]
Hi @MaxReinisch, sorry for the late response, I've my exams going on from 15th Apr all the way till 15th May, resulting in low contributions. As suggested, I'll grey out the button and write a text below the button suggesting user to select contexts? Sounds cool?

**Comment by anishsarangi** [comment]
Thank you for this PR. But now we are moving in different direction regarding this UI. We can close this PR. If you feel any other improvements need to be done, please make a PR.

**Pull request closed without merging**
