### PR TITLE
(update) UI: Outline Buttons, New Search UI, Custom Scrollbar

### PR DESCRIPTION
**Pull request by thisisayush**
References #309

### CODE REVIEW

**Comment by MaxReinisch** [comment]
I like the changes so far, but there are a few things that seem off.  The search bar seems a little odd with only the bottom border. Make that quick change and I'd be happy to merge.

The other thing I want to address is use of force-push.  You shouldn't need to use it.  Currently if I merged, it would undo the setting phrasing change commit I made the other day.  I am not sure why you would need to force push in this case, but if you are having merge conflicts, then try pulling upstream master and resolving any conflicts.

**Comment by thisisayush** [comment]
I'll try and add some action to the bottom buttons and probably the social icons too. Will also see if I can get the search bar look pretty.

I squashed last 3 commits of my own branch because they contained some Changes which shouldn't be there, so I've to use the force push, now this seems to mess up, I'll try and fix that up.

**Comment by MaxReinisch** [comment]
Great.  I think the social icons already have some action.  

No worries about the commit history.  Git is hard, so I am making a contributor's guide.  It's good that you were using a separate branch, but try to remember to swap over to another branch when doing unrelated changes.  See if you can do anything about the commit history on your own.

**Comment by thisisayush** [comment]
I could help with the contribution guide, we have one for our open source community ALiAS. Check it out: https://github.com/asetalias/asetalias.github.io#guidelines

I'll see if I can fix the commit history : )

**Comment by thisisayush** [comment]
@MaxReinisch Please check if this is what you expected in terms of commit history?

**Comment by thisisayush** [comment]
image

Search Box UI Improved
The share icons changes color and zoom in on hover
The settings icon spins on hover
About and Feedback darkens on hover

**Comment by anishsarangi** [comment]
Thank you for this PR. But now we are moving in different direction regarding this UI and feature. We can close this PR. If you feel any other improvements need to be done, please make a PR.

**Pull request closed without merging**
