### PR TITLE
added code beautification

### PR DESCRIPTION
**Pull request by rja907**
Hi!
My name is Raj. 
I am a CS undergrad and I found this project on GSoC Organizations page. 
I am interested in working on this project during the summer.

- To initiate that process, I have made the code more legible so that it is easier to contribute to the repo.
- I have some plans of updating the design. I am thinking of ways to improve the extension and reading reviews of users so that this extension can be made more user-centric.
- Also, I found that on some sites, it takes way too long to process the sitemap functionality. I am thinking of giving the user an alert that it might take a long time before there is any response.

**Let me know if there is there anything that you'd want me to look into in particular.**

Best regards,
Raj

### CODE REVIEW

**Comment by AnkitKhatri55555** [comment]
@rja907 , adding seperate file for css looks legit and necessary

**Comment by abhidas17695** [comment]
Thank you for this pull request @rja907   . If you feel any more stuff needs improvement please make the required pull requests

**Comment by rja907** [comment]
@AnkitKhatri55555: Thanks for the reply. Highly appreciated.
@abhidas17695: You're welcome. I was in the middle of exams so I wasn't able to do much work. Now, I'm back at it.

So, as a Web Developer, I thought that the extension need a better UI. 
This is what I came up with in some hours.

In the new commit, I have done the following work:
- Gave a new UI
screen shot 2018-03-15 at 4 37 25 pm

- I used this extension on different websites to understand what problems one might face. I immediately felt that the flow of action buttons needs to be the same and not varied ie. opening in a new window. For this purpose, I decided to make all the buttons open up in a new tab where the user won't be limited to a 200px width (or 400px width in my commit).

- I felt that this is something that should give an 'archived' look, which is why I changed the font-family.

- Also, after using this extension, I felt that I had to keep on reminding myself what different action buttons did. So, I categorised them in such a way that people can use the extension fast and without much thought of navigating through the UI.

What I plan to do ahead:
- Use this extension even more to understand the flaws and make it seamless. 
- (Obviously) Make a iterative UI changes.
- Add even more support using the D3 library and make the modal better.
- Find new ways to improve the extension and reading reviews of users so that this extension can be made more user-centric. 
- Integrate more features from the the main website like donations etc.

Let me know what you thought about it. Any suggestion/comment will be highly appreciated. :)

**Comment by abhidas17695** [comment]
Good work @rja907

**Pull request closed without merging**
