### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Ritvyk**
Added '<a> tag' for instagram social media page.

### CODE REVIEW

**Comment by thisisayush** [comment]
@Ritvyk Doesn't #329 #330 and #331 seem to do the same task i.e. Adding Instagram Button

**Comment by Ritvyk** [comment]
@thisisayush index.html created the button index.css , I created a button format in it check out btn-instagram and in popup.js I added the functionality to it. I hope you got that.

**Comment by MaxReinisch** [comment]
@Ritvyk, Please make one PR per issue, feature, or bug fix.  You can make a PR with more than 1 commit, and you can commit more than 1 file at a time.

**Comment by anishsarangi** [comment]
Thank you for this PR. But now we are moving in different direction regarding this UI and feature. We can close this PR. If you feel any other improvements need to be done, please make a PR.

**Pull request closed without merging**
