### PR TITLE
Space added between the attributes

### PR DESCRIPTION
**Pull request by divyabaid16**
Fix: #92

### CODE REVIEW

**Comment by abhidas17695** [comment]
Thank you for this pull request @divyabaid16  . If you feel any more stuff needs improvement please make the required pull requests

**Comment by AnkitKhatri55555** [comment]
@divyabaid16 , Only a single line needs updation.You need to check again.

**Comment by divyabaid16** [comment]
@AnkitKhatri55555 , I think that the closing tag </style> is also missing.

**Comment by AnkitKhatri55555** [comment]
@divyabaid16 , the closing seems to be deleted and then re inserted

**Comment by vbanos** [comment]
Thank you for finding this bug, due to conflicts with other merged code, I just did the fix myself 
https://github.com/internetarchive/wayback-machine-chrome/pull/130
and now I'm closing this.

**Pull request closed without merging**
