### PR TITLE
Review

### PR DESCRIPTION
**Pull request by sankalpdayal5**
Indentation and formatting done for all files
lang="en" (or variant) to the html start tag added along with 
Minor bug fixes like semicolon and missing brackets

### CODE REVIEW

**Comment by sankalpdayal5** [comment]
Validation issues in Javascript file sequences.js #104
The align attribute on the tr element is obsolete #102
Unclosed element #98 
Misplaced non-space characters inside a table #96
Unclosed element all_urls #95
adding lang="en" (or variant) to the html start tag #94
Code in index.html is not properly indented and formatted #75
Code in background.js is not properly indented and formatted #73

All above issues are solved

**Comment by anishsarangi** [comment]
Thank you for this PR. If you feel more improvements can be done, feel free to make a PR.

**Comment by vbanos** [comment]
I'm sorry but you cannot make a PR touching 15 files at once, there will certainly be a conflict as it happened.

I'm sorry but the indentation of HTML is not a significant improvement. Can you find ways to:
* Reduce the HTML markup we use without altering the UI of the app?
* Remove redundant CSS?
* Remove redundant JS?
These would be valuable improvements and there is certainly a lot of potential. Then we could look into indentation.

Thank you!

**Comment by sankalpdayal5** [comment]
Ok Thanks. I will look into it.

**Pull request closed without merging**
