### PR TITLE
made changes in ui, added badge and added some alexa and whois features to the extension ,added sharing feature to context menu

### PR DESCRIPTION
**Pull request by deadshourya**
screenshot from 2018-03-08 00-49-25
the ui of the menu has been changed to make it aligned.
screenshot from 2018-03-11 00-13-09 screenshot from 2018-03-11 00-13-40 screenshot from 2018-03-11 00-13-02

### CODE REVIEW

**Comment by VishnuRaghavan** [comment]
Hey, The UI looks good but The search bar and the logo, we could change the layout a little bit and make it cooler. I was thinking like we could add more width and align them properly!

**Comment by deadshourya** [comment]
screenshot from 2018-03-10 18-21-22
i have changed the width to 190px

**Comment by abhidas17695** [comment]
Thank you for this pull request @deadshourya. Can you tell me what do the badges signify ? If you feel any more stuff needs improvement please make the required pull requests.

**Comment by deadshourya** [comment]
The badges shows if the webpage is available in internet archive or not. The green tick mark represents that the webpage is available, red cross mark represents it's not.

**Comment by abhidas17695** [comment]
I get it. Thank you !

**Comment by deadshourya** [comment]
ezgif com-video-to-gif
added feature to show traffic rank and search traffic in extension

**Comment by abhidas17695** [comment]
Nice addition @deadshourya

**Comment by deadshourya** [comment]
ezgif com-video-to-gif 1
added feature to to show brief description (whois) of the web page inside the extension

**Pull request closed without merging**
