### PR TITLE
Exclude UP & DOWN keys from event

### PR DESCRIPTION
**Pull request by tikhsuP**
1. Fixes [this](https://github.com/internetarchive/wayback-machine-chrome/pull/619#pullrequestreview-451174366), enabling the user to go further down the search-box list.
2. Hides "Using Search URL" text when not using search box url.

### CODE REVIEW

**Comment by cgorringe** [comment]
The up & down keys work now, but I'm also seeing that the list box oftentimes disappears entirely. For example it'll show as I type `google` but then disappears after including the period on `google.` or `google.com` (adding the period also displays "Using Search URL" which is fine.)

**Comment by anishsarangi** [comment]
@cgorringe I think that is fixed in #619.

**Comment by tikhsuP** [comment]
The long link text used to go beyond the desired DOM, like this:

Screenshot (137)

I have fixed this by pushing the text to another line.

**Comment by tikhsuP** [comment]
I have merged 'master' and resolved conflicts.

**Pull request merged**
