### PR TITLE
Integrated Wayback Machine's site search

### PR DESCRIPTION
**Pull request by gureks**
User can now directly search any site on Wayback Machine's search

### CODE REVIEW

**Comment by gureks** [comment]
@collinx are you referring to [this](https://web-beta.archive.org/)?

**Comment by collinx** [comment]
@gureks yes, I am referring to that.

**Comment by gureks** [comment]
I'll work on this but let's wait for the repository maintainers' review.

**Comment by gureks** [comment]
Hi @markjohngraham 
Even after your merge, this piece of code is not there in the [branch](https://github.com/internetarchive/wayback-machine-chrome/tree/v1.3.3/). 
I'm pushing another commit to this PR so that the code is updated.

**Comment by rgpt** [comment]
@markjgraham @rchrd2 @gureks 
Just to make it clear for us that 
do we want our users to **search by going to a new tab altogether** and after that if **he wants to share or to see any overview which we can be seen from extension only** then he has to open the extension again and then see those information.
Are these multiple transition good from user's perspective ?.

**Comment by abhidas17695** [comment]
According to me its better if the search results are displayed inside the extension window itself instead of opening a new tab. Opening a new tab to display the results defeats the purpose of integrating the extension with the site search.

**Pull request merged**
