### PR TITLE
Context options refurbish

### PR DESCRIPTION
**Pull request by sr6033**
Now the user can select the context options from the extension itself. No need to open settings page every time to change options. This leads to better and easy use of the feature by a user. They can easily add or remove context options when they want to see them. 
Issue: #348

image
image

### CODE REVIEW

**Comment by sr6033** [comment]
@MaxReinisch 
Can you have a look and see if this is good?

**Comment by Zerichen** [comment]
I also came up with a similar idea after seeing the discussion about issue #348 haha. In this way, the user can quickly change the context options based on their needs. Anyway, Good job!

**Comment by sr6033** [comment]
Yup @Zerichen. Ease of use.

**Comment by MaxReinisch** [comment]
I like it.  I am going to ping @markjgraham for this to see what he thinks.

**Comment by MaxReinisch** [comment]
@sr6033 after using this some more, I realized a couple of things.  

1) This breaks the settings documentation.  If you can get the tooltips on the popup, that would be great.  If not, then delete the code that is trying to do this rather then let it throw errors.  
2) The drop down menu is a little jarring.  It would look fantastic with a drop down animation.  
3) The popup is now getting a little long.  I don't know how avoidable this is, and probably the best way to fix this would be condensing the WBM features into a single row in a different PR.  That being said, I do think that in this PR, the new context button can take up less room on average, while also requiring fewer clicks to use.  I think if the button functioned the way it used to, but there was a carrot button to display the context settings next to it, that would mean it is not necessary to open the context setting drop down every time you use the feature.  I hope I'm explaining this concept clearly, but if not, please ask for clarification.

**Comment by sr6033** [comment]
@MaxReinisch I understood your first 2 points and fix them in the next PR. I would like you to help me out in understanding the 3rd point a bit more clearly.

**Comment by MaxReinisch** [comment]
Instead of putting the "Show me context" button at the bottom of the context settings, put it above the toggle dropdown button.  

Then instead of having 2 rows of buttons, condense it to 1 row, with a dropdown button with the carrot (v) next to the "Show me context button."  If you are using bootstrap grid layouts, maybe make the "show me context" size 8 or 9 and the dropdown button size 3 or 4 (so long as they add up to 12 )

**Comment by sr6033** [comment]
@MaxReinisch I got you now. I will send in a PR with the fix. 
And about this - 
> The popup is now getting a little long.
I will have to think about it on how it can be condensed in the present UI. Although, this can be easily accomplished in my newer Refurbished UI as the design supports collapsing of categories.

**Pull request merged**
