### PR TITLE
Fixing issue/314

### PR DESCRIPTION
**Pull request by Zerichen**

### CODE REVIEW

**Comment by MaxReinisch** [comment]
@Zerichen The implementation is good.  That being said, when working on an issue or feature for the extension, you should checkout a branch and work in that branch instead of master.  This will allow you to work on multiple things, and you won't need commits like a588325, or all these merges.  

I am also curious as to all the changes in /package-lock.json.

**Comment by Zerichen** [comment]
> @Zerichen The implementation is good. That being said, when working on an issue or feature for the extension, you should checkout a branch and work in that branch instead of master. This will allow you to work on multiple things, and you won't need commits like [a588325](https://github.com/internetarchive/wayback-machine-chrome/commit/a588325c5c413680c62232bbe014d5f2eb1c6c10), or all these merges.
> 
> I am also curious as to all the changes in /package-lock.json.

Hi @MaxReinisch, thank you for your quick review! In fact, I did create a branch named issue/314 in my forked repository but I merged it to my own master before making this PR which seems stupid due to my poor contribution experience. I will carefully check the documentation next time! Should I make a new PR instead?

**Comment by MaxReinisch** [comment]
@Zerichen No problem, git takes some getting used to.  I am actually writing a contribution guide to help clarify things like this.  

Yes, if you could push your changes from issue/314 with `git push origin issue/314`, and then make a PR from that branch, that will hopefully have a much cleaner commit history.

**Comment by Zerichen** [comment]
Sure!

**Pull request closed without merging**
