### PR TITLE
Redesigned tag cloud feature

### PR DESCRIPTION
**Pull request by tanweer919**
Redesigned the tag cloud page.
**Screenshot**
Peek 2019-04-20 20-14

### CODE REVIEW

**Comment by tanweer919** [comment]
@MaxReinisch can u review this change.

**Comment by Zerichen** [comment]
@tanweer919 Wow, this plugin looks great, thanks!

**Comment by thisisayush** [comment]
@tanweer919 Nice work there. It looks really cool. @MaxReinisch take a look.

Also, @tanweer919 check if there's a minified version available for the library you used, we can reduce the size of the overall extension.

**Comment by tanweer919** [comment]
@thisisayush minified the library from 14kb down to 4kb.

**Comment by MaxReinisch** [comment]
@tanweer919, @anishsarangi pointed out that the words should scale in size proportionally to how often they are used.  I reverted the merge.  Please implement this, and I'll be happy to merge another PR

**Comment by tanweer919** [comment]
@MaxReinisch @anishsarangi tried implementing the requested change. Now the words scale proportionally to their frequency. #373 is it good??

**Pull request merged**
