### PR TITLE
Added support for automatic URL archival and visual feedback

### PR DESCRIPTION
**Pull request by mrinaldhar**
- Provides user with visual feedback based on if we have archived a URL or not
- Automatically archives URLs that are not in the Wayback Machine

### CODE REVIEW

**Comment by mrinaldhar** [comment]
Visual feedback is provided using badges:


- screen shot 2017-03-15 at 1 36 36 am Processing URL...


- screen shot 2017-03-15 at 1 36 42 am URL exists in Wayback Machine!


- screen shot 2017-03-15 at 1 37 05 am URL does not exist in Wayback Machine.


- screen shot 2017-03-15 at 1 37 12 am URL has now been auto-saved to Wayback Machine!

**Comment by mrinaldhar** [comment]
@markjohngraham  @rchrd2 Please review this PR and let me know if more work needs to be done regarding this.

**Comment by rakesh-chinta** [comment]
This is a neat feature in regard to the user's side, it looks like there is a conflict with the "scripts/background.js", please let me know when its fixed, thank you and great work!

**Comment by vbanos** [comment]
Thank you for this for your PR but this functionality is no longer relevant.

**Pull request closed without merging**
