### PR TITLE
Issue/312: search box is now available

### PR DESCRIPTION
**Pull request by Zerichen**
Adding the search box support. Right now it has the same functionality as the one in Wayback Machine homepage. Meanwhile, I have also optimized the running time of display_list function from 1.9ms to 0.8ms.

### CODE REVIEW

**Comment by MaxReinisch** [comment]
Good work @Zerichen. One thing I'd love to see added is selecting from the drop down menu using the arrow keys.  It would be nice if you see the top result is something you want, to just be able to click the down arrow to select it. Similar to how on github, if one were to type "@", there is a dropdown list created that can be selected using the arrow keys.  If this change would take some major refactoring, let me know and I will merge this PR and the suggestion I am making can be done in a separate PR.

**Comment by Zerichen** [comment]
@MaxReinisch I totally understand that! I will see how to implement it and give you the detailed feedback asap.

**Comment by tanweer919** [comment]
@MaxReinisch can i include jquery UI to resolve this issue??

**Comment by Zerichen** [comment]
@tanweer919 You can create a new PR for it if you want since I still need several days to work on something else.

**Comment by tanweer919** [comment]
@MaxReinisch @Zerichen  I fixed the issue and created a PR #337

**Pull request closed without merging**
