### PR TITLE
Added button to get an overview of all archives of the URL

### PR DESCRIPTION
**Pull request by abhidas17695**
A button is provided in the popup to obtain the overview of all the archives of the URL
captureoverview1

Clicking on the button will provide details about the number of times the URL was archived in each year , in each month and in each day. The final results will be the time of day in which the snapshot was taken.
captureoverview2

Clicking on the final time will render the archived snapshot in a new tab.

### CODE REVIEW

**Comment by markjohngraham** [comment]
Very nice!

How does not this clobber (overwrite) the social media sharing buttons?

**Comment by abhidas17695** [comment]
@markjohngraham 
Sir , I forked the repository before the social media buttons were added. Hence the merge conflicts. I will rectify this.

**Comment by markjohngraham** [comment]
Thank you.  But/and... please don't call me "Sir" :-)

"Mark" is just fine! 

And... great work.

**Comment by abhidas17695** [comment]
@markjohngraham 
Mark , I know its extremely unprofessional of me to be asking this of you on GitHub but could you please review my GSoC proposal ? I sent you two e-mails on 30th March. I am apologetic for being so late. In truth I didn't know about GSoC. I started working on the code just on 24th March. I gave my draft for review on the GSoC portal as well but I have got no response. I know its extremely late but it would be amazing if you could review my draft and give me feedback before the submission deadline so that I may still have a chance of being selected. I sent the e-mail from abhidas17695@gmail.com. I will send it again if you wish. Please forgive me for being so callous and thank you in advance.

**Comment by markjohngraham** [comment]
HI Abhishek... thank you for your inquiry.  I just responded to you via email.

**Comment by abhidas17695** [comment]
@markjohngraham 
Thanks for replying. I have replied to you via e-mail and sent you a public link to my draft. I hope you send me feedback soon. Thanks

**Comment by abhidas17695** [comment]
After resolving the merge conflicts , the button for getting the overview of all archives is present below the social media buttons

**Comment by abhidas17695** [comment]
The latest commit resolved the merge conflicts. The interface is little different 
new2overview
@markjohngraham  please review this commit

**Comment by rakesh-chinta** [comment]
@abhidas17695 , I think we should merge this feature, looks good after the update!

**Comment by abhidas17695** [comment]
@rakesh-chinta  I must resolve the merge conflicts first

**Comment by rakesh-chinta** [comment]
@abhidas17695 yup, lets get those conflicts fixed and out of the way

**Comment by vbanos** [comment]
Obsolete, already implemented. Thank you.

**Pull request closed without merging**
