### PR TITLE
Whois, Alexa, API, Data-Scrapping, UI Customization and Cache Integration

### PR DESCRIPTION
**Pull request by rohitcoder**
Hi,
I noticed that This extension is launching popups for each feature. If you want to see whois detail you will get popup, if you want to see Alexa details again popup. 
This is frustrating for users and of course affecting your quality.

Thats why i removed popups and created one API for getting all whois data and the interesting thing is you can host this API yourself. I was looking for whois data API and every API was Paid and wayback machine will never agree to use those third parties because of dependency and pricing.  That's why i created API for your extension how it works?

1. You pass site name into API (https://rohitcoder.cf/research/whois_api/index.php?site=edvoid.com)
2. It fetches data from Whois.com (Data-scrapping) 

3 It returns data in JSON format to Chrome extension
4. We represent those data

Same thing i will do for Twitter search, Alexa and I will also add Google+Bing Top 3 results from search (without any popups)

Applying for #GsoC2018

### CODE REVIEW

**Comment by rohitcoder** [comment]
I also added my whois data API code which is located in host folder.

**Comment by rohitcoder** [comment]
image
@markjgraham @vbanos New Updates Coming Soon   :sunglasses: 
I hope you all will like this new update like the previous one

**Comment by rohitcoder** [comment]
Hi, My new update is here...

1. Integrated Alexa API with Chrome Extension
2. You can Check Alexa and Whois API Codes from host folder
imageimageimageimage


For more Snapshots Please check snap_shots directory 

Next update coming soon...

@markjgraham  @vbanos Please verify these new PRs

**Comment by abhidas17695** [comment]
Thank you for this pull request @rohitcoder  . If you feel any more stuff needs improvement please make the required pull requests.

**Comment by rohitcoder** [comment]
Related PR - #100  
@abhidas17695  @vbanos  new update here
Updated Index UI, Loading UI, Alexa Data UI, Whois Data UI
Fixed bugs minor bugs related to Search feature and About page. (JS wasn't working)
Working on next update - Customizable theme, user can edit themes directly from extension and data will be saved in local storage using chrome API

imageimageimageimage

**Comment by rohitcoder** [comment]
@abhidas17695  @markjgraham  Again a new update
This Update was really tough and it took lots of time for me. I added auto cache feature for my data-scrapping methods (because usually, it takes a lot of time) i also did some great changes like
```javascript
 chrome.storage.local.set //  Now we are using this because it has 5,242,880 QUOTA_BYES Limit available
```
```javascript
chrome.storage.sync.set // we removed this API because it had few limits like only 102,400 QUOTA_BYTES were available
```
# Have a look at the attached video (Demo) how its working
[Wayback Machine Chrome Extension](https://www.youtube.com/watch?v=zIOB6gTuUUg&feature=youtu.be)

In next update i will implement this same cache system in whois data api and i will come with customizable theme settings (Because now i am ready to work with chrome.storage.sync.set)

>> Rohit Kumar
>> Have a Good Day!

**Comment by rohitcoder** [comment]
# Introducing Customizations With Reset options and Cache Management
ezgif-4-e45b1849cd
@abhidas17695  @markjgraham 
As I promised, This is my another one update now user can customize look and feel of this extension themselves! In this update, i also included Some reset features like **bReset Customizations** or **Reset Everything** (Which will clear all cache data so that extension can load fresh data)

## In this above image, you can see two features working
1. Customization
2. Reset Everything / Reset Customziation option

> Thanks,
> Rohit Kumar (@rohitcoder)

**Comment by rohitcoder** [comment]
@abhidas17695 @markjgraham I added new commits again.
In this updated I Included
1. Whois feature now also supports automatic cache
2. Updated Search UI List-View
3. Few code optimizations like Removing unusual .bak files from project and replaced internal stylesheet with an external stylesheet
4. Am also trying to decrease size and code length of files so that it can render fast for best performance below is short example code am using it for same purpose **Alexa** and as well as for **Whois**. Note here am not creating a lot of unusual functions for each feature.
image


### In next update i will try to include Safety and Security Rating (**By Norton**)
This will help any user to identify that any particular website is safe or not.

>Thanks,
>Rohit Kumar

**Comment by rohitcoder** [comment]
I started working on **Remote Configuration feature** Which i mentioned in My GSOC Proposal.

image

I am sure, this will help your team alot to manage extension updates & Features remotely.

**Pull request closed without merging**
