### PR TITLE
Fixed arrow keys issue within the dropdown

### PR DESCRIPTION
**Pull request by tanweer919**
Up and down arrow key is now working as they were supposed to. I included jquery UI to make it work.
#suggestion-box was not needed after refactoring, so ultimately removed it.
Screenshot:
Screenshot from 2019-04-14 02-27-57

### CODE REVIEW

**Comment by tanweer919** [comment]
@MaxReinisch @Zerichen

**Comment by Zerichen** [comment]
Looks good. I was thinking about using plain javascript to implement this at first and don't know there is a jQuery API doing this.

**Comment by tanweer919** [comment]
Yeah jquery UI provides a flexible solution which can be configured pretty easily.

**Comment by Zerichen** [comment]
Cool, then after merging our two PRs the search box will come back to life I think.

**Comment by tanweer919** [comment]
Yeah i hope so that these two PRs will be merged.

**Comment by sr6033** [comment]
This is cool @tanweer919 
This makes the search simpler.

**Comment by tanweer919** [comment]
Thanks man @sr6033.
This will go well with your refurbished UI.

**Comment by sr6033** [comment]
Yup. I am just waiting for all these PRs to be merged. Then I will try to remove the conflicts and make additional changes.

**Comment by MaxReinisch** [comment]
In the future, please don't work from your master branch.  Make a separate branch for whatever change you want to do, and make a PR from that.  Once that happens, I will merge.

**Comment by tanweer919** [comment]
@MaxReinisch done #349

**Pull request merged**
