### PR TITLE
Removed duplicate code from tagcloud context

### PR DESCRIPTION
**Pull request by anishsarangi**
@vbanos I have removed `jqcloud-1.0.4.min.js` and some unnecessary/commented code from tagcloud context. Please have a look at it !!
Next step will be optimising the code and adding unit test to tagcloud

### CODE REVIEW

**Comment by vbanos** [comment]
You forgot to remove it from
```
tagcloud.html:        <link rel="stylesheet" type="text/css" href="css/jqcloud.css">
```

Also, you forgot to remove file `css/jqcloud.css`

**Comment by anishsarangi** [comment]
@vbanos I have already removed it 
 `<link rel="stylesheet" type="text/css" href="css/jqcloud.css">`
I just removed `jqcloud.css` from css folder. 
Thanks.!

**Comment by vbanos** [comment]
I'm sorry, I wanted to say that there is a reference to jqcloud.css in `singleWindow.html`.
I removed that:
https://github.com/internetarchive/wayback-machine-chrome/pull/193

**Comment by anishsarangi** [comment]
Thank you.!!

**Pull request merged**
