### PR TITLE
Optimized tag's weight find concept and fix tag-cloud issue in single page view

### PR DESCRIPTION
**Pull request by sr6033**
Removed the function findWeightOf() as it is no longer needed now. Now the complexity has reduced from O(n x m) to O(m).

### CODE REVIEW

**Comment by sr6033** [comment]
@MaxReinisch 
Can you check this out?

**Comment by sr6033** [comment]
The 2nd commit fixes the issue #336

**Comment by MaxReinisch** [comment]
Good job 👍

**Comment by anishsarangi** [comment]
Good work @sr6033 . Also please remember to make two separate PRs for addressing two separate issues.
Thank you.

**Comment by sr6033** [comment]
Okay, @anishsarangi. I will keep that in mind from now on.

**Pull request merged**
